version: "3.8"

services:
  spring-web-service:
    container_name: web-con
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORTS=8080
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_DB=employeedb
      - MYSQL_USER_NAME=root
      - MYSQL_PASSWORD=root
    depends_on:
      - mysql-service
    networks:
      web-net:
    restart: on-failure

  mysql-service:
    container_name: mysql-con
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeedb
    ports:
      - "3307:3306"
    networks:
      web-net:




networks:
  web-net:

volumes:
  db:
